### ISSUE TITLE
idk how to write thsi lol can anyone help thanks!

### ISSUE THREAD

**Issue by rollrz** [rollrz/IP-addres-finder#1]

**Comment by darksh71** [comment]
import requests

def get_public_ip():
    try:
        # Use an external service to get your public IP address
        response = requests.get('https://api64.ipify.org?format=json')
        
        # Parse the JSON response
        data = response.json()
        public_ip = data['ip']
        
        return public_ip
    except Exception as e:
        return str(e)

if __name__ == '__main__':
    public_ip = get_public_ip()
    if public_ip:
        print(f'Your public IP address is: {public_ip}')
    else:
        print('Unable to retrieve your public IP address.')
